version: '3.4'

services:
  rabbitmq:
    container_name: market-rabbitmq
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data 
    networks:
      - network

  postgres:
    container_name: market-postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root   
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  ksu.market.api:
    container_name: market-api
    image: ${DOCKER_REGISTRY-}ksumarketapi
    build:
      context: .
      dockerfile: Ksu.Market.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network


  ksu.market.products:
    container_name: market-products
    image: ${DOCKER_REGISTRY-}ksumarketproducts
    build:
      context: .
      dockerfile: Ksu.Market.Products/Dockerfile
    depends_on:
      - postgres
    networks:
      - network

  ksu.market.reviews:
    container_name: market-reviews
    image: ${DOCKER_REGISTRY-}ksumarketreviews
    build:
      context: .
      dockerfile: Ksu.Market.Reviews/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:  

