version: '3.4'

services:
  ksu.market.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050:80"

  ksu.market.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5051:80"

