version: '3.4'

services:
  rabbitmq:
    container_name: market-rabbitmq
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data 
    networks:
      - network

  postgres:
    container_name: market-postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root   
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - network

  ksu.market.api:
    container_name: market-api
    image: ${DOCKER_REGISTRY-}ksumarketapi
    build:
      context: .
      dockerfile: Ksu.Market.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 


networks:
  network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:  